services:
  pihole:
    image: pihole/pihole:latest 
    environment:
      file: .env
    volumes:
      - ./etc-pihole/:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    network_mode: host 